env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
steps:
  - group: ":test_tube: Tests"
    key: "tests"
    steps:
      - label: ":golangci-lint: lint :lint-roller:"
        key: "lint"
        command: |
          - cd generate;
          - golangci-lint run -vv --timeout "10m" --config=.golangci.yaml;
        plugins:
          - docker#v5.11.0:
              image: "registry.hub.docker.com/golangci/golangci-lint:v1.59.1"
              environment:
                - "GOTOOLCHAIN=auto"
